version: '3' # Docker compose version

services:
  # =============== Our Nest app ===============
  nest_app:
    container_name: nest-app # Container name
    ports:
      # Local & container ports for nest app
      - "3000:3000"
    environment:
      # Environment Variables
      - DATABASE_HOST=postgresdb
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres_db
    depends_on:
      # Wait until depending app running
      - postgresdb
    volumes:
      - ../src:/usr/src/app/src:ro # Using Hot-Reload
      # Ensures that the node_modules directory is kept intact inside the container.
      - /usr/src/app/node_modules

  # =============== Our Postgres db ===============
  postgresdb:
    image: postgres # Postgres latest images
    container_name: postgres
    ports:
      # Local & container ports for postgres db
      - "5432:5432"
      - "127.0.0.1:5431:5432"
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresdb_data:/var/lib/postgresql/data

# Create volumes
volumes:
  postgresdb_data:
